src/OnPremise/WebSite/Areas/Admin/ViewModels/DelegationViewModel.cs
using System.Linq;

namespace Thinktecture.IdentityServer.Web.Areas.Admin.ViewModels
{
    public class DelegationViewModel
    {
        private Repositories.IDelegationRepository delegationRepository;

        public DelegationViewModel(Repositories.IDelegationRepository delegationRepository)
        {
            this.delegationRepository = delegationRepository;
        }

        DelegationUser[] users;
        public DelegationUser[] Users
        {
            get
            {
                if (users == null)
                {
                    users = delegationRepository
                        .GetAllUsers(-1, -1)
                        .Select(x => new DelegationUser { Username = x })
                        .ToArray();
                }
                return users;
            }
        }
    }

    public class DelegationUser
    {
        public string Username { get; set; }
        public bool Delete { get; set; }
    }
}

src/OnPremise/WebSite/Areas/Admin/Controllers/DelegationController.cs
using System;
using System.ComponentModel.Composition;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
using Thinktecture.IdentityModel.Authorization.Mvc;
using Thinktecture.IdentityServer.Models;
using Thinktecture.IdentityServer.Repositories;
using Thinktecture.IdentityServer.Web.Areas.Admin.ViewModels;

namespace Thinktecture.IdentityServer.Web.Areas.Admin.Controllers
{
    [ClaimsAuthorize(Constants.Actions.Administration, Constants.Resources.Configuration)]
    public class DelegationController : Controller
    {
        [Import]
        public IUserManagementRepository userManagementRepository { get; set; }
        [Import]
        public IDelegationRepository delegationRepository { get; set; }

        public DelegationController()
        {
            Container.Current.SatisfyImportsOnce(this);
        }

        public DelegationController(IDelegationRepository delegationRepository, IUserManagementRepository userManagementRepository)
        {
            this.delegationRepository = delegationRepository;
            this.userManagementRepository = userManagementRepository;
        }

        public ActionResult Index()
        {
            var vm = new DelegationViewModel(this.delegationRepository);
            return View("Index", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string action, DelegationUser[] users)
        {
            if (action == "new") return Configure();
            if (action == "delete") return Delete(users);
            return RedirectToAction("Index");
        }

        private ActionResult Delete(DelegationUser[] users)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    foreach (var user in users.Where(x => x.Delete))
                    {
                        var settings = this.delegationRepository.GetDelegationSettingsForUser(user.Username);
                        foreach (var setting in settings)
                        {
                            this.delegationRepository.Delete(setting);
                        }
                    }
                    TempData["Message"] = Resources.DelegationController.DelegationUsersDeleted;
                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", Resources.DelegationController.ErrorDeletingDelegationUsers);
                }
            }

            return Index();
        }

        public ActionResult Configure(string id = null)
        {
            var vm = new DelegationSettingsForUserViewModel(this.delegationRepository, this.userManagementRepository, id);
            return View("Configure", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(DelegationSetting model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    this.delegationRepository.Add(model);
                    TempData["Message"] = Resources.DelegationController.RealmAdded;
                    return RedirectToAction("Configure", new { id = model.UserName });
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch
                {
                    ModelState.AddModelError("", Resources.DelegationController.ErrorAddingDelegationSetting);
                }
            }

            var vm = new DelegationSettingsForUserViewModel(this.delegationRepository, this.userManagementRepository, model.UserName);
            return View("Configure", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Remove(DelegationSetting model)
        {
            try
            {
                this.delegationRepository.Delete(model);
                TempData["Message"] = Resources.DelegationController.RealmDeleted;
                return RedirectToAction("Configure", new { id = model.UserName });
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            catch
            {
                ModelState.AddModelError("", Resources.DelegationController.ErrorDeletingDelegationSetting);
            }

            var vm = new DelegationSettingsForUserViewModel(this.delegationRepository, this.userManagementRepository, model.UserName);
            return View("Configure", vm);
        }
    }
}

src/OnPremise/WebSite/Areas/Admin/Views/Delegation/Configure.cshtml
@model DelegationSettingsForUserViewModel
@using Thinktecture.IdentityServer.Web.Areas.Admin.App_LocalResources.Delegation
@using Thinktecture.IdentityServer.Web.Utility

@{
    if (Model.IsNew)
    {
        ViewBag.Title = Configure_cshtml.NewDelegationConfiguration;
    }
    else
    {
        ViewBag.Title = string.Format(Configure_cshtml.DelegationConfigurationForUser, Model.UserName);
    }
}


@Html.ValidationSummary(Configure_cshtml.ErrorCreatingDelegationConfiguration)

<fieldset class="editor small">
    <legend>@ViewBag.Title</legend>
    @using (Html.BeginForm("Add", "Delegation"))
    {
        @Html.AntiForgeryToken()
        var model = new Thinktecture.IdentityServer.Models.DelegationSetting()
        {
            UserName = Model.UserName
        };

        if (Model.IsNew)
        {
            <div class="edit-prop">
                @Html.LabelFor(x => model.UserName)
                @Html.DropDownListFor(x => model.UserName, Model.AllUserNames)
                @Html.ValidatorFor(x => model.UserName)
            </div>
        }
        else
        {
            <div class="edit-prop">
                @Html.HiddenFor(x => model.UserName)
                @Html.LabelFor(x => model.UserName)
                @Html.DisplayFor(x => model.UserName)
            </div>
        }
        
        <div class="edit-prop">
            @Html.LabelFor(x => model.Description)
            @Html.EditorFor(x => model.Description)
            @Html.ValidatorFor(x => model.Description)
        </div>
        <div class="edit-prop">
            @Html.LabelFor(x => model.Realm)
            @Html.EditorFor(x => model.Realm)
            @Html.ValidatorFor(x => model.Realm)
        </div>
        <div class="buttons">
            <button type="submit">@Configure_cshtml.AddRealm</button>
            <button type="reset">@Configure_cshtml.Cancel</button>
        </div>
    }
    <hr />

    @foreach (var model in Model.DelegationSettings)
    {
        using (Html.BeginForm("Remove", "Delegation"))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => model.UserName)
            <div class="edit-prop">
                @Html.LabelFor(x => model.Description)
                @Html.DisplayFor(x => model.Description)
                @Html.HiddenFor(x => model.Description)
            </div>
            <div class="edit-prop">
                @Html.LabelFor(x => model.Realm)
                @Html.DisplayFor(x => model.Realm)
                @Html.HiddenFor(x => model.Realm)
            </div>
            <div class="buttons">
                <button type="submit">@Configure_cshtml.DeleteRealm</button>
            </div>            
        }
    }

</fieldset>

src/OnPremise/WebSite/Areas/Admin/Views/Delegation/Index.cshtml
@using Thinktecture.IdentityServer.Web.Areas.Admin.App_LocalResources.Delegation
@model DelegationViewModel

@{
    ViewBag.Title = Index_cshtml.DelegationAccounts;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(Index_cshtml.ErrorDeletingDelegationUsers)

    <fieldset class="editor">
        <legend>@ViewBag.Title</legend>

        @for (int i = 0; i < Model.Users.Length; i++)
        {
            <div>
                @Html.HiddenFor(x => Model.Users[i].Username)
                @Html.LabelFor(x => Model.Users[i].Delete, Model.Users[i].Username)
                @Html.CheckBoxFor(x => Model.Users[i].Delete)
                @Html.ActionLink("configure", "Configure", new { id = Model.Users[i].Username })
            </div>
        }

        <div class="buttons">
            <button type="submit" name="action" value="delete">@Index_cshtml.DeleteSelected</button>
            <button type="submit" name="action" value="new">@Index_cshtml.New</button>
            <button type="reset">@Index_cshtml.Cancel</button>
        </div>
    </fieldset>
}